AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Image Resize Lambda

  Lambda function that resizes images on S3 upload

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name for image uploads
  DynamoDBTableName:
    Type: String
    Description: DynamoDB table name for image metadata
    Default: Images

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024

Resources:
  ImageResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_code/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTableName
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
        - S3WritePolicy:
            BucketName: !Ref S3BucketName
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTableName
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref S3BucketName
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - index.ts
        External:
          - sharp

Outputs:
  ImageResizeFunction:
    Description: "Image Resize Lambda Function ARN"
    Value: !GetAtt ImageResizeFunction.Arn
  ImageResizeFunctionRole:
    Description: "IAM Role for Image Resize Lambda Function"
    Value: !GetAtt ImageResizeFunctionRole.Arn
